name: Private payment CI

on:
    workflow_dispatch:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: CHECKOU REPOSITORY
            uses: actions/checkout@v4

          - name: DEFINIR VERSÃO DO NODE.JS
            uses: actions/setup-node@v4
            with:
              node-version: "20.x"

          - name: INSTALAR DEPENDENCIAS
            run: npm install

          - name: INICIAR API
            run: npm start &

          - name: AGUARDAR A API INICIAR
            run: sleep 10